name: minihackathon 2022 Website Development CI/CD

on:
  push:
    branches: [development]
permissions: 
  contents: write
    
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: Development
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
#       - name: Upload a Build Artifact
#         uses: actions/upload-artifact@v2.3.0
#         with:
#           name: build
#           path: build
      
#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.4.0
#       - name: Download a Build Artifact
#         uses: actions/download-artifact@v2.1.0
#         with:
#           name: build
#           path: build
#       - name: Deploy 🚀
#         uses: JamesIves/github-pages-deploy-action@v4.3.3
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: build # The folder the action should deploy.
          
          
# name: Node.js CI
# on:
#   push:
#     branches: [development]

# jobs:
#   build-test-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Set-up Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: "10.x"
#       - run: npm install
#       - run: npm run build
#       - run: npm test
#       - name: Deploy
#         uses: crazy-max/ghaction-github-pages@v1
#         with:
#           target_branch: gh-pages
#           build_dir: build
#         env:
#           GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
